apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoresponse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoresponse
  template:
    metadata:
      labels:
        app: todoresponse
    spec:
      containers:
        - name: todoresponse
          image: atteh0gm4n/todoresponse
          env:
            - name: DEMO_GREEING
              value: "Hello from the environment!"