apiVersion: v1
kind: Service
metadata:
  name: todoresponse-svc
spec:
  type: NodePort
  selector:
    app: todoresponse
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3000