apiVersion: v1
kind: Service
metadata:
  name: todoresponse-svc
spec:
  type: ClusterIP
  selector:
    app: todoresponse
  ports:
    - name: http
      port: 1234
      protocol: TCP
      targetPort: 3000
